### PR TITLE
Fn Metrics with Grafana move and clean up

### PR DESCRIPTION
**Pull request by sachin-pikle**

### CODE REVIEW

**Comment by sachin-pikle** [comment]
Based on the comments in https://github.com/fnproject/fn/pull/792, I think it's best to leave the prometheus yaml and grafana dashboard son files in the fn/examples/grafana directory .. And just update the tutorials/grafana to refer/point to that location instead of moving things over. Let me know if you agree and I will make the relevant modifications and submit a revised PR.

**Comment by sachin-pikle** [comment]
Made changes to refer to prometheus.yml file and the 3 dashboard json files from fn/examples/grafana

**Comment by sachin-pikle** [comment]
Made changes to refer to prometheus.yml file and the 3 dashboard json files from fn/examples/grafana

Mike - Can you try out this version and let me know? Hopefully it's good to be merged.

**Comment by shaunsmith** [comment]
I like the approach of using curl to pull prometheus and grafana files from git rather than requiring users to clone the entire repo.  Nice!

But please move the prometheus/grafana tutorial back to the bottom of the Tutorials README.md.  This order of the tutorials is from easier to harder and this is definitely not the tutorial to do immediately after installing Fn. 😄

**Comment by michael-w-williams** [comment]
I agree with Shaun. Move the Grafana tutorial last. I think I would also make the Java tutorial second. 

I'm testing the lab but got stuck on the Prometheus install. It is a Docker issue completely unrelated to anything Fn as far as I can tell.  Took me a while to figure it out so I'm calling it a day. The information on the problem and fix is parked here: <https://github.com/michael-w-williams/notes/wiki/Docker-Issue-with-Fn-UI-Grafana-Prometheus-Lab>

I think you are good to go for a merge. If I find anything we can just do another PR.

**Comment by sachin-pikle** [comment]
I left the Java Tutorial position as-is for now. I agree we can move it up. I think at #3 position just after Intro and Applications.

**Pull request merged**
