### PR TITLE
Fix to node tutorial for changes to triggers

### PR DESCRIPTION
**Pull request by michael-w-williams**
Fixes a link a several changes to how triggers are named.

Also fixes:
* <https://github.com/fnproject/tutorials/issues/178>
* <https://github.com/fnproject/tutorials/issues/179>

### CODE REVIEW

**Comment by sachin-pikle** [comment]
Hi @michael-w-williams .. I have verified and tested .. Changes look good. Thank you for taking care of this at such a short notice. A few comments that you can fix along with this issue:

1. I noticed that my "default" context had a legacy API URL with the suffix **/v1**. And then all API/CLI calls will fail with a 404 error - Path not found: POST **/v1**/v2/apps ... 
CURRENT	NAME		PROVIDER	API URL							REGISTRY
	default		default		http://localhost:8080/v1				fndemouser 

I had to update the API URL to http://localhost:8080 to resolve the error. Your node tutorial edits show the correct API URL but people like me who have an old setup are likely to trip over this. I see that we haven't updated "Configuring your context" section on this page https://github.com/fnproject/tutorials/blob/master/install/README.md#configure-your-context

2. echo -n '{"name":"Bob"}' | fn invoke nodeapp nodefn --content-type application/json

Invoke works even without "--content-type application/json"

3. curl -H "Content-Type: application/json" http://localhost:8080/t/nodeapp/nodefn

This works without -H "Content-Type: application/json"

4. curl -H "Content-Type: application/json" -d '{"name":"Bob"}' http://localhost:8080/t/nodeapp/nodefn-trigger

This works without -H "Content-Type: application/json"

**Comment by michael-w-williams** [comment]
@sachin-pikle I'll do the context fix. About the json stuff. Are the FDKs going to default to json as the data type?   The last time I updated the tutorials the word was not guarantied thus the content/type stuff.

**Comment by sachin-pikle** [comment]
Ok. I don't know the plan for FDK's so let's leave it as is for now.

**Comment by AlexanderHodicke** [comment]
Thanks for resolving the issues so quickly!! Looks all good to me now.

BR, Alex

**Pull request merged**
