### PR TITLE
fdk-python tutorial

### PR DESCRIPTION
**Pull request by denismakogon**

### CODE REVIEW

**Comment by rioscesar** [comment]
@denismakogon I attempted your tutorial and came across a couple problems. 

On, 

> "You can find more information and code samples here and read more about Fn formats here."

The "here" link does not work. It takes me to a 404 github page. 

Also when attempting to run this command: 

`echo 'test' | fn --verbose run --format json`

I get back: 

```Building image fndemouser/pythonfn:0.0.1 
Sending build context to Docker daemon  6.144kB
Step 1/6 : FROM python:3.6
 ---> c1e459c00dc3
Step 2/6 : WORKDIR /function
 ---> Using cache
 ---> 3fd61bd2d332
Step 3/6 : ADD requirements.txt /function/
 ---> Using cache
 ---> 46d335453f71
Step 4/6 : RUN pip3 install -r requirements.txt
 ---> Using cache
 ---> 93584f9518b5
Step 5/6 : ADD . /function/
 ---> c9c758ce09af
Step 6/6 : ENTRYPOINT python3 func.py
 ---> Running in 7e8143d3f4f6
 ---> 803a7dec8150
Removing intermediate container 7e8143d3f4f6
Successfully built 803a7dec8150
Successfully tagged fndemouser/pythonfn:0.0.1

ERROR: Format json not supported
```

Might be a flag issue. Running: 

`fn deploy --local --app myapp` 

and 

`curl -v http://localhost:8080/r/myapp/pythonfn -d 'test'`

give me the desired output.

**Comment by denismakogon** [comment]
That was CLI problem, necessary PRs were merged and it works fine at this moment.

**Comment by denismakogon** [comment]
@michael-w-williams @shaunsmith can you review this one, please?

**Comment by michael-w-williams** [comment]
Denys. Sorry this took so long for me to review. Shaun noticed this PR in our UI/UA meeting yesterday. So I read through the Readme.md and it reads good to me. You might want to consider moving the Getting Started sections to the front of the file.  I think hands on before a detailed explanation of the FDK might be better. But it is up to you.  Also, I suggest you add the pip3 FDK installation as a step. That is obvious to Python folks, but may not be to others.

**Comment by michael-w-williams** [comment]
About Testing. When I tried "fn run" I get an "ERROR: exit status 245". Also, `fn` is complaining it doesn't understand `--format json` parameter. Probably some sort of configuration thing I'm missing. Ping me if you need more details.

**Comment by denismakogon** [comment]
@michael-w-williams 

> You might want to consider moving the Getting Started sections to the front of the file

I think, we need to explain what the FDK is in first place, then `Getting started` (will rename that to `Create function's boilerplate`), the rest should remain the same to keep the structure of this tutorial correct.

> Also, I suggest you add the pip3 FDK installation as a step. That is obvious to Python folks, but may not be to others.

There's the notion that FDK works only with Python 3.5 or greater, so any other references to any Python tool don't have to come with specific version notes.

**Comment by denismakogon** [comment]
@michael-w-williams you are running old Fn CLI for sure.

**Comment by denismakogon** [comment]
This is what makes it work:
```
fn version
Client version:  0.4.45
Server version:  0.3.325
```

**Comment by denismakogon** [comment]
Doh, CLI PR still not merged https://github.com/fnproject/cli/pull/136

**Comment by michael-w-williams** [comment]
Aha! :)  I can retest once there is a merge if you want. Let me know.

**Comment by denismakogon** [comment]
@michael-w-williams tutorial update with respect to recent CLI changes related to Python.

**Pull request merged**
