### PR TITLE
Flow 101 fix to cope with the last Flow API.

### PR DESCRIPTION
**Pull request by delabassee**
Fix for #134, Flow 102 will be done next.

### CODE REVIEW

**Comment by denismakogon** [comment]
@michael-w-williams can you please check what's going on with github/pages check.

**Comment by delabassee** [comment]
@michael-w-williams can you check this?

**Comment by michael-w-williams** [comment]
I've asked Thom about this and cc'ed both of you. By the way, I can merge this if you think its ready. Let me know.

**Comment by delabassee** [comment]
Can you just quickly go through the wordings before merging?

**Pull request merged**
